---
title: "Untitled"
author: "anonymous"
date: "2023-11-08"
output: html_document
---

```{r}
r = raster(bio1)
thresh = 0.5
values(r) = 0
out_dirs = list.dirs("C://Users/dunga/species-dist-modeling/birds/out", recursive=FALSE)
aucs = rep(0, length(out_dirs))
for (i in 1:length(out_dirs)) {
  tryCatch({
    d = out_dirs[i]
    auc = read.csv(paste(d,"/maxentResults.csv",sep=""))$Training.AUC
    aucs[i] = auc
    if (auc >= 0.7) {
      raster_file = list.files(d, pattern="*.asc")
      raster_species = raster(paste(d,"/",raster_file,sep=""))
      r = r + (raster_species > thresh)
    }
  }, error=function(e){
    print(e)
  }, warning=function(w){
    print(w)
  })
}
```

```{r}
writeRaster(r, "C://Users/dunga/species-dist-modeling/birds/richness.asc")
```

```{r}
plot(r)
```

```{r}
png("C://Users/dunga/species-dist-modeling/plots/birds_richness.png")
plot(cut(r, breaks=c(0, 50, 150, 300)), col=rev(terrain.colors(4)[1:3]), legend = FALSE, main="Birds Richness")
legend("topright", legend = c("R <= 50", "50 < R <= 150", "R > 150"), fill=rev(terrain.colors(4)[1:3]))
dev.off()
```
```{r}
hist(aucs[aucs != 0])
```
```{r}
sum(aucs >= 0.7)/length(aucs)
```

```{r}
corrs = rep(0, 19)
for (i in 1:19) {
  env = values(climate_finland)[,i]
  corrs[i] = stats::cor(x=env, y=values(r), use="na.or.complete")
}
```

```{r}
cbind(1:19,corrs)[order(corrs, decreasing = T),]
```
```{r}
vars = rep("", 19)
for (i in 1:19) {
  vars[i] = paste("BIO", i, sep="")
}
vars
```
```{r}
corrs_df = data.frame(var=vars, corr=round(corrs, 2))
corrs_df
```

```{r}
png("C://Users/dunga/species-dist-modeling/plots/birds_corr.png")
corrs_df$var = factor(corrs_df$var, levels = corrs_df$var)
ggplot(data=corrs_df, aes(x=var, y=corr)) + geom_col(fill="darkslategray1") +
  geom_text(aes(label = corr), vjust=-0.3, size=3) + theme(axis.text.x = element_text(angle = 40, size=9)) + labs(x="Variables", y="Correlation", title="Correlation of Bioclimatic Variables with Species Richness")
dev.off()
```
```{r}
png("C://Users/dunga/species-dist-modeling/plots/birds_richness.png")
plot(r, main="Birds richness", ylab="Richness")
dev.off()
```
```{r}
for (i in 1:19) {
  png(paste("C://Users/dunga/species-dist-modeling/plots/bio",i,".png",sep=""))
  plot(climate_finland[[i]], main=paste("BIO",i,sep=""))
  dev.off()
}
```


```{r}
plot(r, main="Birds richness")
plot(climate_finland$bio11, main="BIO11") #Mean Temperature of Coldest Quarter
plot(climate_finland$bio6, main="BIO6") #Min Temperature of Coldest Month
plot(climate_finland$bio9, main="BIO9") #Mean Temperature of Driest Quarter
plot(climate_finland$bio1, main="BIO1") #Annual Mean Temperature
plot(climate_finland$bio7, main="BIO7") #Temperature Annual Range (BIO5-BIO6)
plot(climate_finland$bio2, main="BIO2") #Mean Diurnal Range (Mean of monthly (max temp - min temp))
```
```{r}

```

