---
title: "Untitled"
author: "anonymous"
date: "2023-11-08"
output: html_document
---
```{r}
bio1 = raster("C://Users/dunga/species-dist-modeling/env-rasters/bio1.grd")
```


```{r}
r = raster(bio1)
values(r) = 0
res = read.csv("C://Users/dunga/species-dist-modeling/mammals/out/maxentResults.csv")
aucs = read.csv("C://Users/dunga/species-dist-modeling/mammals/out/maxentResults.csv")$Training.AUC
cut_off = 0.5
for (i in 1:length(aucs)) {
  tryCatch({
    s = res$Species[i]
    raster_species = raster(paste("C://Users/dunga/species-dist-modeling/mammals/out/",s,".asc",sep=""))
    if (aucs[i] >= 0.7) {
      r = r + (raster_species >= cut_off)
    }
  }, error=function(e){
    print(e)
  }, warning=function(w){
    print(w)
  })
}
```

```{r}
png("C://Users/dunga/species-dist-modeling/plots/mammals_richness.png")
plot(r, main="Mammals richness", ylab="Richness")
dev.off()
```
```{r}
hist(aucs[aucs != 0])
```
```{r}
sum(aucs >= 0.7)/length(aucs)
```
```{r}
plot(r)
```


```{r}
writeRaster(r, "C://Users/dunga/species-dist-modeling/mammals/richness.asc")
```

```{r}
corrs = rep(0, 19)
for (i in 1:19) {
  env = values(climate_finland)[,i]
  corrs[i] = stats::cor(x=env, y=values(r), use="na.or.complete")
}
```

```{r}
cbind(1:19,corrs)[order(corrs, decreasing = T),]
```
```{r}
par(mfrow = c(2, 3))
plot(r)
plot(climate_finland$bio11) #Mean Temperature of Coldest Quarter
plot(climate_finland$bio6) #Min Temperature of Coldest Month
plot(climate_finland$bio9) #Mean Temperature of Driest Quarter
plot(climate_finland$bio7) #Temperature Annual Range (BIO5-BIO6)
plot(climate_finland$bio4) #Temperature Seasonality (standard deviation ×100)
```

```{r}
corrs_df = data.frame(var=vars, corr=round(corrs, 2))
corrs_df
```


```{r}
png("C://Users/dunga/species-dist-modeling/plots/mammals_corr.png")
corrs_df$var = factor(corrs_df$var, levels = corrs_df$var)
ggplot(data=corrs_df, aes(x=var, y=corr)) + geom_col(fill="darkslategray1") +
  geom_text(aes(label = corr), vjust=-0.3, size=3) + theme(axis.text.x = element_text(angle = 40, size=9)) + labs(x="Variables", y="Correlation", title="Correlation of Bioclimatic Variables with Species Richness")
dev.off()
```

```{r}
plot(r)
```



```{r}
r = raster("C://Users/dunga/species-dist-modeling/mammals/richness.asc")
```


```{r}
png("C://Users/dunga/species-dist-modeling/plots/mammals_richness.png")
plot(cut(r, breaks=c(0, 30, 50, 100)), col=rev(terrain.colors(4)[1:3]), legend = FALSE, main="Mammals Richness")
legend("topright", legend = c("R <= 30", "30 < R <= 50", "R > 50"), fill=rev(terrain.colors(4)[1:3]))
dev.off()
```


